name: Finance Lakehouse dbt CI

on:
  workflow_dispatch:
    inputs:
      domain:
        description: "Data domain to run (fred or stooq)"
        required: true
        type: choice
        options:
          - fred
          - stooq

jobs:
  dbt-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt
        run: |
          pip install --upgrade pip
          pip install dbt-athena-community==1.9.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 🔴 THIS IS THE FIX — DO NOT MOVE IT
      - name: Clean Athena CTAS temp data
        run: aws s3 rm s3://finance-lake-query-vk1911eu/tables/ --recursive || true

      - name: Install dbt packages
        working-directory: dbt/finance_dbt
        run: dbt deps

      - name: dbt debug
        working-directory: dbt/finance_dbt
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ATHENA_S3_QUERY_RESULTS: ${{ secrets.ATHENA_S3_QUERY_RESULTS }}
        run: dbt debug

      - name: Run dbt models
        working-directory: dbt/finance_dbt
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ATHENA_S3_QUERY_RESULTS: ${{ secrets.ATHENA_S3_QUERY_RESULTS }}
        run: |
          dbt run --select tag:${{ github.event.inputs.domain }}

      - name: Run dbt tests
        working-directory: dbt/finance_dbt
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ATHENA_S3_QUERY_RESULTS: ${{ secrets.ATHENA_S3_QUERY_RESULTS }}
        run: |
          dbt test --select tag:${{ github.event.inputs.domain }}
